name: Compile LaTeX
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: 01_Academics/Semester_1/Mathematics_for_Computing/05_Assignments/Assignment_01/main.tex

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Assignment-01-PDF
          path: 01_Academics/Semester_1/Mathematics_for_Computing/05_Assignments/Assignment_01/main.pdf
